apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-persistent-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/test/output/result'
