version: '3.4'

networks:
  qa:

services:
  # InfluxDB is a fast time-series database
  influxdb2:
    image: influxdb:2
    networks:
      - qa
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=qa-test
      - DOCKER_INFLUXDB_INIT_BUCKET=QA
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
